before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    id: duplo-jit
    main: ./cmd/duplo-jit
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: 'duplo-jit'
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    id: duplo-aws-credential-process
    main: ./cmd/duplo-aws-credential-process
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: 'duplo-aws-credential-process'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
changelog:
  skip: false
  filters:
    exclude:
      - '^\[release\] '
      - '^\[cicd\] '
      - '^Merge tag '
      - '^Merge branch '
      - '^bump '
announce:
  slack:
    enabled: true
    channel: '#engineering'
release:
  draft: false
brews:
  - name: duplo-jit
    goarm: 6
    goamd64: v1
    tap:
      owner: duplocloud
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/duplocloud/duplo-jit/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: duplo-bot
      email: infra+github-bot@duplocloud.net
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/duplocloud/duplo-jit"
    description: "Command-line tools for JIT Duplo, AWS and Kubernetes access"
    license: "MIT"
    test: |
      system "duplo-jit version"
